"""Models

Revision ID: 037faeb4771f
Revises: 6547c7634d94
Create Date: 2025-06-18 09:31:11.542614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '037faeb4771f'
down_revision = '6547c7634d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klientname', sa.String(length=64), nullable=False),
    sa.Column('number_phone', sa.String(length=120), nullable=False),
    sa.Column('VIP_status', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIP_status'),
    sa.UniqueConstraint('klientname')
    )
    op.create_table('menenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menengername', sa.String(length=64), nullable=False),
    sa.Column('number_phone', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('group'))

    op.drop_table('student')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('user')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('data', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('time')
        batch_op.drop_column('data')
        batch_op.drop_column('type')

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('patronymic', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('group', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('group'), ['group'], unique=True)

    op.drop_table('menenger')
    op.drop_table('klient')
    # ### end Alembic commands ###
