"""Убрал DATA = DATE

Revision ID: 51035aa90e18
Revises: ced069e28929
Create Date: 2025-06-21 09:18:22.644502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51035aa90e18'
down_revision = 'ced069e28929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', mysql.TIME(), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.String(length=64),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
