"""Tg_id

Revision ID: 7c0845bb2201
Revises: 51035aa90e18
Create Date: 2025-06-23 09:02:38.873595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0845bb2201'
down_revision = '51035aa90e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
