"""car

Revision ID: 8dc6557bf76b
Revises: 7c0845bb2201
Create Date: 2025-06-23 09:15:58.479302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc6557bf76b'
down_revision = '7c0845bb2201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car', sa.String(length=60), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.drop_column('car')

    # ### end Alembic commands ###
