"""Add table

Revision ID: ced069e28929
Revises: 037faeb4771f
Create Date: 2025-06-19 12:17:54.388503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ced069e28929'
down_revision = '037faeb4771f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('VIP_status'))
        batch_op.drop_index(batch_op.f('klientname'))

    with op.batch_alter_table('menenger', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('klient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('klientname'), ['klientname'], unique=True)
        batch_op.create_index(batch_op.f('VIP_status'), ['VIP_status'], unique=True)

    # ### end Alembic commands ###
