"""Add table

Revision ID: d74e1863faac
Revises: 8dc6557bf76b
Create Date: 2025-06-26 11:55:03.342527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd74e1863faac'
down_revision = '8dc6557bf76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menenger', schema=None) as batch_op:
        batch_op.drop_column('number_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menenger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_phone', mysql.VARCHAR(length=120), nullable=False))

    # ### end Alembic commands ###
